env:
  browser: true
  es2021: true
  webextensions: true
extends:
  - eslint:recommended
  - google
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  max-len: 0
plugins:
  - eslint-plugin-jsdoc
